language: node_js
node_js:
  - 6
  - 8
  - 9
  - 10
cache:
  directories:
  - node_modules

before_script:
- npm run lint

script:
- npm run system-test
- npm run coverage
- npm run ensure-coverage

after_script:
- npm run upload-coverage
