language: node_js
node_js:
  - 4
  - 5
  - 6

cache:
  directories:
  - node_modules

before_script:
- npm run lint

script:
- npm run test
- npm run system-test
- npm run ensure-coverage
- npm run report-coverage

after_script:
- npm run upload-coverage
